/*
 * Physical Letters - a Skyrim SKSE plugin for writing letters to NPCs,
 * having them delivered, and receiving their replies through SkyrimNet.
 * Copyright (C) 2026 Zevick
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "DebugKeys.h"
#include "HandIn.h"
#include "Parchment.h"
#include "Postage.h"
#include "NpcLetters.h"
#include "NpcToNpc.h"
#include "RoadCourier.h"
#include "Config.h"
#include "Papyrus.h"
#include "DynamicForms.h"
#include "Letters.h"
#include "Serialization.h"
#include "Session.h"
#include "SkyrimNet.h"
#include "TextHook.h"
#include "Transit.h"
#include "Writing.h"

#include <spdlog/sinks/basic_file_sink.h>
#include <thread>

namespace {

    constexpr auto kHeartbeat = std::chrono::seconds(2);

    // Every kHeartbeat, on the game thread, for the life of the process: Poll makes a
    // started session ready; Tick delivers and reads letters in a ready one.
    void StartHeartbeat()
    {
        std::thread([]() {
            while (true) {
                std::this_thread::sleep_for(kHeartbeat);
                SKSE::GetTaskInterface()->AddTask([]() {
                    // An exception must not cross into the engine.
                    try {
                        PhysicalLetters::Session::Poll();
                        PhysicalLetters::Transit::Tick();
                        PhysicalLetters::NpcLetters::Tick();
                        PhysicalLetters::NpcToNpc::Tick();
                        PhysicalLetters::RoadCourier::Tick();
                    } catch (const std::exception& e) {
                        SKSE::log::error("Heartbeat failed: {}", e.what());
                    }
                });
            }
        }).detach();
    }

    void OnMessage(SKSE::MessagingInterface::Message* msg)
    {
        if (!msg) return;
        switch (msg->type) {
        case SKSE::MessagingInterface::kPostLoad:
            PhysicalLetters::Writing::Connect();
            break;
        case SKSE::MessagingInterface::kDataLoaded:
            PhysicalLetters::SkyrimNet::Init();
            PhysicalLetters::Letters::CheckTemplate();
            PhysicalLetters::DebugKeys::Register();
            PhysicalLetters::HandIn::Register();
            PhysicalLetters::Parchment::OnDataLoaded();
            PhysicalLetters::Writing::Register();
            StartHeartbeat();
            break;
        case SKSE::MessagingInterface::kPreLoadGame:
            PhysicalLetters::Session::End();
            break;
        case SKSE::MessagingInterface::kNewGame:
            PhysicalLetters::Session::End();
            PhysicalLetters::Session::Start();
            PhysicalLetters::Postage::ApplyPrice();
            PhysicalLetters::HandIn::ApplyDialogue();
            break;
        case SKSE::MessagingInterface::kPostLoadGame:
            // World copies of our letters in the loaded cells were built before the load
            // callback filled the forms in.
            DynamicForms::RebuildLoadedWorldCopies();
            PhysicalLetters::Session::Start();
            PhysicalLetters::Postage::ApplyPrice();
            PhysicalLetters::HandIn::ApplyDialogue();
            break;
        default:
            break;
        }
    }

    void InitializeLog()
    {
        auto path = SKSE::log::log_directory();
        if (!path) {
            return;
        }

        *path /= "PhysicalLetters.log"sv;
        auto sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(path->string(), true);

        auto log = std::make_shared<spdlog::logger>("global log"s, std::move(sink));
        log->set_level(spdlog::level::info);
        log->flush_on(spdlog::level::info);

        spdlog::set_default_logger(std::move(log));
        spdlog::set_pattern("[%H:%M:%S] [%l] %v"s);

        const auto* plugin = SKSE::PluginDeclaration::GetSingleton();
        SKSE::log::info("{} v{}", plugin->GetName(), plugin->GetVersion());
    }
}

// SKSEPlugin_Version and SKSEPlugin_Query are auto-generated by add_commonlibsse_plugin
// in CMakeLists.txt via cmake/CommonLibSSE.cmake — do NOT declare them manually here.

SKSE_PLUGIN_LOAD(const SKSE::LoadInterface* a_skse)
{
    InitializeLog();

    // log = false: InitializeLog already set up our logger, and CommonLib's own
    // would replace it (and reopen the same file).
    SKSE::Init(a_skse, { .log = false });

    // Written straight back: MO2 puts it in overwrite/, where mod updates don't replace it.
    auto* config = PhysicalLetters::Config::GetSingleton();
    config->Load(std::filesystem::current_path() / "Data" / "SKSE" / "Plugins" / "PhysicalLetters.ini");
    config->Save();
    if (config->Get(PhysicalLetters::Config::kDebugLog)) {
        // Debug lines are flushed too, or they sit in the buffer until the next info line.
        spdlog::default_logger()->set_level(spdlog::level::debug);
        spdlog::default_logger()->flush_on(spdlog::level::debug);
    }

    PhysicalLetters::Papyrus::Register();

    PhysicalLetters::Serialization::Register();
    PhysicalLetters::TextHook::Install();
    SKSE::GetMessagingInterface()->RegisterListener(OnMessage);

    return true;
}
